services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - yii2-network
    command: >
              /bin/sh -c "composer install &&
              php yii migrate --interactive=0 &&
              apache2-foreground"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: platform
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      - yii2-network
    healthcheck:
      test: [ "CMD", "mysql", "-uuser", "-puser_password", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - '8080:80'
    networks:
      - yii2-network
    depends_on:
      db:
        condition: service_started

networks:
  yii2-network:

volumes:
  db_data: